// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// WARNING! Do not edit this file manually, your changes will be overwritten.

#include "graphqlservice/GraphQLService.h"

#include "ValidationSharedTypes.h"

#include <algorithm>
#include <array>
#include <cstddef>
#include <functional>
#include <stdexcept>
#include <string_view>
#include <utility>
#include <vector>

using namespace std::literals;

namespace graphql {
namespace service {

static const auto s_namesDogCommand = validation::getDogCommandNames();
static const auto s_valuesDogCommand = validation::getDogCommandValues();

template <>
validation::DogCommand Argument<validation::DogCommand>::convert(const response::Value& value)
{
	if (!value.maybe_enum())
	{
		throw service::schema_exception { { R"ex(not a valid DogCommand value)ex" } };
	}

	const auto result = internal::sorted_map_lookup<internal::shorter_or_less>(
		s_valuesDogCommand,
		std::string_view { value.get<std::string>() });

	if (!result)
	{
		throw service::schema_exception { { R"ex(not a valid DogCommand value)ex" } };
	}

	return *result;
}

template <>
service::AwaitableResolver Result<validation::DogCommand>::convert(service::AwaitableScalar<validation::DogCommand> result, ResolverParams&& params)
{
	return ModifiedResult<validation::DogCommand>::resolve(std::move(result), std::move(params),
		[](validation::DogCommand value, const ResolverParams&)
		{
			const auto idx = static_cast<size_t>(value);

			if (idx >= s_namesDogCommand.size())
			{
				throw service::schema_exception { { R"ex(Enum value out of range for DogCommand)ex" } };
			}

			return ResolverResult { { response::ValueToken::EnumValue { std::string { s_namesDogCommand[idx] } } } };
		});
}

template <>
void Result<validation::DogCommand>::validateScalar(const response::Value& value)
{
	if (!value.maybe_enum())
	{
		throw service::schema_exception { { R"ex(not a valid DogCommand value)ex" } };
	}

	const auto [itr, itrEnd] = internal::sorted_map_equal_range<internal::shorter_or_less>(
		s_valuesDogCommand.begin(),
		s_valuesDogCommand.end(),
		std::string_view { value.get<std::string>() });

	if (itr == itrEnd)
	{
		throw service::schema_exception { { R"ex(not a valid DogCommand value)ex" } };
	}
}

static const auto s_namesCatCommand = validation::getCatCommandNames();
static const auto s_valuesCatCommand = validation::getCatCommandValues();

template <>
validation::CatCommand Argument<validation::CatCommand>::convert(const response::Value& value)
{
	if (!value.maybe_enum())
	{
		throw service::schema_exception { { R"ex(not a valid CatCommand value)ex" } };
	}

	const auto result = internal::sorted_map_lookup<internal::shorter_or_less>(
		s_valuesCatCommand,
		std::string_view { value.get<std::string>() });

	if (!result)
	{
		throw service::schema_exception { { R"ex(not a valid CatCommand value)ex" } };
	}

	return *result;
}

template <>
service::AwaitableResolver Result<validation::CatCommand>::convert(service::AwaitableScalar<validation::CatCommand> result, ResolverParams&& params)
{
	return ModifiedResult<validation::CatCommand>::resolve(std::move(result), std::move(params),
		[](validation::CatCommand value, const ResolverParams&)
		{
			const auto idx = static_cast<size_t>(value);

			if (idx >= s_namesCatCommand.size())
			{
				throw service::schema_exception { { R"ex(Enum value out of range for CatCommand)ex" } };
			}

			return ResolverResult { { response::ValueToken::EnumValue { std::string { s_namesCatCommand[idx] } } } };
		});
}

template <>
void Result<validation::CatCommand>::validateScalar(const response::Value& value)
{
	if (!value.maybe_enum())
	{
		throw service::schema_exception { { R"ex(not a valid CatCommand value)ex" } };
	}

	const auto [itr, itrEnd] = internal::sorted_map_equal_range<internal::shorter_or_less>(
		s_valuesCatCommand.begin(),
		s_valuesCatCommand.end(),
		std::string_view { value.get<std::string>() });

	if (itr == itrEnd)
	{
		throw service::schema_exception { { R"ex(not a valid CatCommand value)ex" } };
	}
}

template <>
validation::ComplexInput Argument<validation::ComplexInput>::convert(const response::Value& value)
{
	auto valueName = service::ModifiedArgument<std::string>::require<service::TypeModifier::Nullable>("name", value);
	auto valueOwner = service::ModifiedArgument<std::string>::require<service::TypeModifier::Nullable>("owner", value);

	return validation::ComplexInput {
		std::move(valueName),
		std::move(valueOwner)
	};
}

template <>
validation::DefaultInput Argument<validation::DefaultInput>::convert(const response::Value& value)
{
	const auto defaultValue = []()
	{
		response::Value values(response::Type::Map);
		response::Value entry;

		entry = []()
		{
			response::Value elements(response::Type::List);
			response::Value entry;

			return elements;
		}();
		values.emplace_back("values", std::move(entry));
		entry = response::Value(static_cast<int>(42));
		values.emplace_back("count", std::move(entry));
		entry = []()
		{
			response::Value members(response::Type::Map);
			response::Value entry;

			return members;
		}();
		values.emplace_back("child", std::move(entry));
		entry = response::Value(static_cast<int>(9));
		values.emplace_back("required", std::move(entry));

		return values;
	}();

	auto pairValues = service::ModifiedArgument<int>::find<service::TypeModifier::Nullable, service::TypeModifier::List>("values", value);
	auto valueValues = (pairValues.second
		? std::move(pairValues.first)
		: service::ModifiedArgument<int>::require<service::TypeModifier::Nullable, service::TypeModifier::List>("values", defaultValue));
	auto pairCount = service::ModifiedArgument<int>::find<service::TypeModifier::Nullable>("count", value);
	auto valueCount = (pairCount.second
		? std::move(pairCount.first)
		: service::ModifiedArgument<int>::require<service::TypeModifier::Nullable>("count", defaultValue));
	auto pairChild = service::ModifiedArgument<validation::NestedDefaultInput>::find<service::TypeModifier::Nullable>("child", value);
	auto valueChild = (pairChild.second
		? std::move(pairChild.first)
		: service::ModifiedArgument<validation::NestedDefaultInput>::require<service::TypeModifier::Nullable>("child", defaultValue));
	auto pairRequired = service::ModifiedArgument<int>::find("required", value);
	auto valueRequired = (pairRequired.second
		? pairRequired.first
		: service::ModifiedArgument<int>::require("required", defaultValue));

	return validation::DefaultInput {
		std::move(valueValues),
		std::move(valueCount),
		std::move(valueChild),
		valueRequired
	};
}

template <>
validation::NestedDefaultInput Argument<validation::NestedDefaultInput>::convert(const response::Value& value)
{
	const auto defaultValue = []()
	{
		response::Value values(response::Type::Map);
		response::Value entry;

		entry = response::Value(static_cast<int>(7));
		values.emplace_back("count", std::move(entry));

		return values;
	}();

	auto pairCount = service::ModifiedArgument<int>::find<service::TypeModifier::Nullable>("count", value);
	auto valueCount = (pairCount.second
		? std::move(pairCount.first)
		: service::ModifiedArgument<int>::require<service::TypeModifier::Nullable>("count", defaultValue));

	return validation::NestedDefaultInput {
		std::move(valueCount)
	};
}

} // namespace service

namespace validation {

ComplexInput::ComplexInput() noexcept
	: name {}
	, owner {}
{
	// Explicit definition to prevent ODR violations when LTO is enabled.
}

ComplexInput::ComplexInput(
		std::optional<std::string> nameArg,
		std::optional<std::string> ownerArg) noexcept
	: name { std::move(nameArg) }
	, owner { std::move(ownerArg) }
{
}

ComplexInput::ComplexInput(const ComplexInput& other)
	: name { service::ModifiedArgument<std::string>::duplicate<service::TypeModifier::Nullable>(other.name) }
	, owner { service::ModifiedArgument<std::string>::duplicate<service::TypeModifier::Nullable>(other.owner) }
{
}

ComplexInput::ComplexInput(ComplexInput&& other) noexcept
	: name { std::move(other.name) }
	, owner { std::move(other.owner) }
{
}

ComplexInput::~ComplexInput()
{
	// Explicit definition to prevent ODR violations when LTO is enabled.
}

ComplexInput& ComplexInput::operator=(const ComplexInput& other)
{
	ComplexInput value { other };

	std::swap(*this, value);

	return *this;
}

ComplexInput& ComplexInput::operator=(ComplexInput&& other) noexcept
{
	name = std::move(other.name);
	owner = std::move(other.owner);

	return *this;
}


DefaultInput::DefaultInput() noexcept
	: values {}
	, count {}
	, child {}
	, required {}
{
	// Explicit definition to prevent ODR violations when LTO is enabled.
}

DefaultInput::DefaultInput(
		std::optional<std::vector<int>> valuesArg,
		std::optional<int> countArg,
		std::unique_ptr<NestedDefaultInput> childArg,
		int requiredArg) noexcept
	: values { std::move(valuesArg) }
	, count { std::move(countArg) }
	, child { std::move(childArg) }
	, required { std::move(requiredArg) }
{
}

DefaultInput::DefaultInput(const DefaultInput& other)
	: values { service::ModifiedArgument<int>::duplicate<service::TypeModifier::Nullable, service::TypeModifier::List>(other.values) }
	, count { service::ModifiedArgument<int>::duplicate<service::TypeModifier::Nullable>(other.count) }
	, child { service::ModifiedArgument<NestedDefaultInput>::duplicate<service::TypeModifier::Nullable>(other.child) }
	, required { service::ModifiedArgument<int>::duplicate(other.required) }
{
}

DefaultInput::DefaultInput(DefaultInput&& other) noexcept
	: values { std::move(other.values) }
	, count { std::move(other.count) }
	, child { std::move(other.child) }
	, required { std::move(other.required) }
{
}

DefaultInput::~DefaultInput()
{
	// Explicit definition to prevent ODR violations when LTO is enabled.
}

DefaultInput& DefaultInput::operator=(const DefaultInput& other)
{
	DefaultInput value { other };

	std::swap(*this, value);

	return *this;
}

DefaultInput& DefaultInput::operator=(DefaultInput&& other) noexcept
{
	values = std::move(other.values);
	count = std::move(other.count);
	child = std::move(other.child);
	required = std::move(other.required);

	return *this;
}


NestedDefaultInput::NestedDefaultInput() noexcept
	: count {}
{
	// Explicit definition to prevent ODR violations when LTO is enabled.
}

NestedDefaultInput::NestedDefaultInput(
		std::optional<int> countArg) noexcept
	: count { std::move(countArg) }
{
}

NestedDefaultInput::NestedDefaultInput(const NestedDefaultInput& other)
	: count { service::ModifiedArgument<int>::duplicate<service::TypeModifier::Nullable>(other.count) }
{
}

NestedDefaultInput::NestedDefaultInput(NestedDefaultInput&& other) noexcept
	: count { std::move(other.count) }
{
}

NestedDefaultInput::~NestedDefaultInput()
{
	// Explicit definition to prevent ODR violations when LTO is enabled.
}

NestedDefaultInput& NestedDefaultInput::operator=(const NestedDefaultInput& other)
{
	NestedDefaultInput value { other };

	std::swap(*this, value);

	return *this;
}

NestedDefaultInput& NestedDefaultInput::operator=(NestedDefaultInput&& other) noexcept
{
	count = std::move(other.count);

	return *this;
}

} // namespace validation
} // namespace graphql
